/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    collections: Collection;
    plants: Plant;
    'story-blocks': StoryBlock;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    plants: PlantsSelect<false> | PlantsSelect<true>;
    'story-blocks': StoryBlocksSelect<false> | StoryBlocksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    brand: Brand;
    hero: Hero;
    'fragrance-page': FragrancePage;
    'gift-page': GiftPage;
    hydroponic: Hydroponic;
    'store-info': StoreInfo;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    brand: BrandSelect<false> | BrandSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'fragrance-page': FragrancePageSelect<false> | FragrancePageSelect<true>;
    'gift-page': GiftPageSelect<false> | GiftPageSelect<true>;
    hydroponic: HydroponicSelect<false> | HydroponicSelect<true>;
    'store-info': StoreInfoSelect<false> | StoreInfoSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  /**
   * 개발자가 구분할 때 쓰는 값입니다. 보통 수정하지 않아도 됩니다.
   */
  slug: string;
  name: string;
  tagline: string;
  image: number | Media;
  alt?: string | null;
  aspectRatio?: string | null;
  href: string;
  /**
   * 숫자가 작을수록 먼저 보입니다.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants".
 */
export interface Plant {
  id: number;
  slug: string;
  name: string;
  koreanName: string;
  category: 'rare' | 'everyday';
  image: number | Media;
  alt?: string | null;
  tagline: string;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  care?: {
    light?: string | null;
    water?: string | null;
    temperature?: string | null;
  };
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-blocks".
 */
export interface StoryBlock {
  id: number;
  slug: string;
  image: number | Media;
  alt?: string | null;
  size: 'wide' | 'portrait';
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'plants';
        value: number | Plant;
      } | null)
    | ({
        relationTo: 'story-blocks';
        value: number | StoryBlock;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  tagline?: T;
  image?: T;
  alt?: T;
  aspectRatio?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plants_select".
 */
export interface PlantsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  koreanName?: T;
  category?: T;
  image?: T;
  alt?: T;
  tagline?: T;
  features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  care?:
    | T
    | {
        light?: T;
        water?: T;
        temperature?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-blocks_select".
 */
export interface StoryBlocksSelect<T extends boolean = true> {
  slug?: T;
  image?: T;
  alt?: T;
  size?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand".
 */
export interface Brand {
  id: number;
  name: string;
  tagline: string;
  shortDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * PC+모바일 공통 슬라이드는 PC용/모바일용을 나눠 넣고, 모바일 전용 슬라이드는 "모바일에서만 보이기"를 켠 뒤 모바일용 이미지에만 넣으세요.
   */
  slides: {
    /**
     * 켜면 PC에서는 숨기고, 아래 모바일용 이미지만 사용합니다.
     */
    mobileOnly?: boolean | null;
    /**
     * 데스크톱(넓은 화면)에서 보이는 이미지입니다.
     */
    desktopImage?: (number | null) | Media;
    /**
     * 휴대폰 화면용 이미지입니다. 모바일 전용 슬라이드면 여기에 넣고, 공통 슬라이드면 선택 사항입니다.
     */
    mobileImage?: (number | null) | Media;
    alt: string;
    objectPosition?: string | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fragrance-page".
 */
export interface FragrancePage {
  id: number;
  eyebrow?: string | null;
  title: string;
  lead: string;
  brands: {
    id?: string | null;
    name: string;
    image: number | Media;
    alt: string;
    href: string;
    logoWidth?: string | null;
    darkLogo?: boolean | null;
  }[];
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-page".
 */
export interface GiftPage {
  id: number;
  eyebrow?: string | null;
  title: string;
  lead: string;
  options: {
    id?: string | null;
    title: string;
    image: number | Media;
    alt: string;
    copy: string;
  }[];
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hydroponic".
 */
export interface Hydroponic {
  id: number;
  title: string;
  description: string;
  image: number | Media;
  alt?: string | null;
  intro?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        sectionId?: string | null;
        title: string;
        blocks?:
          | {
              blockType: 'paragraph' | 'quote' | 'list';
              text?: string | null;
              items?:
                | {
                    title: string;
                    body: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-info".
 */
export interface StoreInfo {
  id: number;
  name: string;
  address: string;
  addressDetail?: string | null;
  hours?:
    | {
        day: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  phone?: string | null;
  mapUrl?: string | null;
  placeUrl?: string | null;
  instagramUrl?: string | null;
  image: number | Media;
  alt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  navItems?:
    | {
        id: string;
        label: string;
        href: string;
      }[]
    | null;
  footerLinks?:
    | {
        id: string;
        label: string;
        href: string;
      }[]
    | null;
  naverStoreUrl?: string | null;
  privacyPolicyUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand_select".
 */
export interface BrandSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  shortDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        mobileOnly?: T;
        desktopImage?: T;
        mobileImage?: T;
        alt?: T;
        objectPosition?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fragrance-page_select".
 */
export interface FragrancePageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  brands?:
    | T
    | {
        id?: T;
        name?: T;
        image?: T;
        alt?: T;
        href?: T;
        logoWidth?: T;
        darkLogo?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gift-page_select".
 */
export interface GiftPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  lead?: T;
  options?:
    | T
    | {
        id?: T;
        title?: T;
        image?: T;
        alt?: T;
        copy?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hydroponic_select".
 */
export interface HydroponicSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  alt?: T;
  intro?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        sectionId?: T;
        title?: T;
        blocks?:
          | T
          | {
              blockType?: T;
              text?: T;
              items?:
                | T
                | {
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-info_select".
 */
export interface StoreInfoSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  addressDetail?: T;
  hours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  phone?: T;
  mapUrl?: T;
  placeUrl?: T;
  instagramUrl?: T;
  image?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        id?: T;
        label?: T;
        href?: T;
      };
  footerLinks?:
    | T
    | {
        id?: T;
        label?: T;
        href?: T;
      };
  naverStoreUrl?: T;
  privacyPolicyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}